exclude: infamous_imps/static
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
        name: TOML Check
      - id: check-yaml
        name: YAML Check
      - id: end-of-file-fixer
        name: Fixing new lines at end of file
      - id: name-tests-test
        name: Check test names
      - id: trailing-whitespace
        name: Trimming whitespaces
        args: [--markdown-linebreak-ext=md]

  -   repo: https://github.com/asottile/pyupgrade
      rev: v2.37.2
      hooks:
      -   id: pyupgrade
          name: Upgrading Syntax

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
        name: Check for Blanket noqa

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Auto-sort Imports

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: Formatting code

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: Checking Code Quality
        additional_dependencies:
          - flake8-docstrings~=1.6.0

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.971
      hooks:
      -   id: mypy
          name: Type Checking
          additional_dependencies: [types-all]
          exclude: ^(docs/|build/)
